"""baseline schema

Revision ID: 6ab752a2f0ca
Revises: 
Create Date: 2026-09-17 11:34:57.886849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab752a2f0ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('universe', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_daily_close', sa.Float(), nullable=True),
    sa.Column('last_daily_price_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('catalyst_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_catalyst_source')
    )
    op.create_index(op.f('ix_catalysts_detected_date'), 'catalysts', ['detected_date'], unique=False)
    op.create_index(op.f('ix_catalysts_ticker_id'), 'catalysts', ['ticker_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('combined_score_at_generation', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('catalyst_ids_at_generation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'run_date', name='uq_explanation_ticker_date')
    )
    op.create_index(op.f('ix_explanations_ticker_id'), 'explanations', ['ticker_id'], unique=False)
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('eps_quarterly', sa.Float(), nullable=True),
    sa.Column('eps_yoy_growth', sa.Float(), nullable=True),
    sa.Column('eps_qoq_growth', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_snapshots_ticker_id'), 'fundamental_snapshots', ['ticker_id'], unique=False)
    op.create_table('institutional_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Date(), nullable=False),
    sa.Column('institution_cik', sa.String(length=20), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('value_usd_k', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'quarter', 'institution_cik', name='uq_inst_holding')
    )
    op.create_index(op.f('ix_institutional_holdings_quarter'), 'institutional_holdings', ['quarter'], unique=False)
    op.create_index(op.f('ix_institutional_holdings_ticker_id'), 'institutional_holdings', ['ticker_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('weinstein_stage', sa.Integer(), nullable=False),
    sa.Column('weinstein_transition', sa.Boolean(), nullable=False),
    sa.Column('weeks_in_stage', sa.Integer(), nullable=False),
    sa.Column('weinstein_ma_slope_pct', sa.Float(), nullable=False),
    sa.Column('weinstein_relative_volume', sa.Float(), nullable=False),
    sa.Column('weinstein_rsi', sa.Float(), nullable=False),
    sa.Column('canslim_criteria', sa.JSON(), nullable=False),
    sa.Column('canslim_score', sa.Integer(), nullable=False),
    sa.Column('canslim_verifiable_count', sa.Integer(), nullable=False),
    sa.Column('canslim_passed_count', sa.Integer(), nullable=False),
    sa.Column('combined_score', sa.Integer(), nullable=False),
    sa.Column('risk_bucket', sa.String(length=16), nullable=False),
    sa.Column('strategies', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'run_date', name='uq_opportunity_ticker_date')
    )
    op.create_index(op.f('ix_opportunities_combined_score'), 'opportunities', ['combined_score'], unique=False)
    op.create_index(op.f('ix_opportunities_run_date'), 'opportunities', ['run_date'], unique=False)
    op.create_index(op.f('ix_opportunities_ticker_id'), 'opportunities', ['ticker_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_spy_price', sa.Float(), nullable=False),
    sa.Column('exit_signal_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_spy_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_status'), 'portfolio_positions', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_positions_ticker_id'), 'portfolio_positions', ['ticker_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_price_ticker_date')
    )
    op.create_index(op.f('ix_price_snapshots_ticker_id'), 'price_snapshots', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_snapshots_ticker_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_portfolio_positions_ticker_id'), table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_status'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_opportunities_ticker_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_run_date'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_combined_score'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_institutional_holdings_ticker_id'), table_name='institutional_holdings')
    op.drop_index(op.f('ix_institutional_holdings_quarter'), table_name='institutional_holdings')
    op.drop_table('institutional_holdings')
    op.drop_index(op.f('ix_fundamental_snapshots_ticker_id'), table_name='fundamental_snapshots')
    op.drop_table('fundamental_snapshots')
    op.drop_index(op.f('ix_explanations_ticker_id'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_catalysts_ticker_id'), table_name='catalysts')
    op.drop_index(op.f('ix_catalysts_detected_date'), table_name='catalysts')
    op.drop_table('catalysts')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    # ### end Alembic commands ###
